### ISSUE TITLE
Real time playback

### ISSUE THREAD

**Issue by pizzapim** [fhunleth/midi_synth#9]
It would be cool to have a way to create MIDI compositions with real time playback from within Elixir.
As you have probably spent more time with Fluidsynth, how feasable do you think this is?
I guess it's needed to write the timing in C, because of BEAM's preemptive scheduler?

**Comment by fhunleth** [comment]
My experience so far with the Erlang VM is that it does surprisingly well, so if I were to write a sequencer, I'd write it in Elixir first and then tweak it if there were issues. You may be interested in this: https://www.youtube.com/watch?v=XN4WuOujr38. Unfortunately, I wrote `midi_synth` near the same time as Matt made his drum machine, so neither of us knew about the other's work until Empex.

Anyway, I totally agree that this would be great to have.

**Comment by pizzapim** [comment]
Wow, what you linked is definitely close to what I was thinking about. And it seems the timing of the VM is indeed sufficient for this purpose. I'll take a look those packages, thanks!

**Comment by pizzapim** [comment]
Hey @fhunleth,
I created a library to easily create a score and play it using Elixir [here](https://github.com/pizzapim/midi_player). Thanks to your work, converting to binary and playing the commands was very easy, so thank you very much! Next I'm going to try and make the actual sequencer in Phoenix LiveView :) If you have any comments or suggestions they are welcome.
